import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Stitch canonical names
        surface:                   '#f9f9ff',
        'surface-bright':          '#f9f9ff',
        'surface-dim':             '#d3daea',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#f0f3ff',
        'surface-container':       '#e7eefe',
        'surface-container-high':  '#e2e8f8',
        'surface-container-highest':'#dce2f3',
        'surface-variant':         '#dce2f3',
        'surface-tint':            '#0053db',
        'on-surface':              '#151c27',
        'on-surface-variant':      '#434655',
        'inverse-surface':         '#2a313d',
        'inverse-on-surface':      '#ebf1ff',
        primary:                   '#004ac6',
        'primary-container':       '#2563eb',
        'primary-fixed':           '#dbe1ff',
        'primary-fixed-dim':       '#b4c5ff',
        'on-primary':              '#ffffff',
        'on-primary-container':    '#eeefff',
        'on-primary-fixed':        '#00174b',
        'on-primary-fixed-variant':'#003ea8',
        'inverse-primary':         '#b4c5ff',
        secondary:                 '#575e70',
        'secondary-container':     '#d9dff5',
        'secondary-fixed':         '#dce2f7',
        'secondary-fixed-dim':     '#c0c6db',
        'on-secondary':            '#ffffff',
        'on-secondary-container':  '#5c6274',
        'on-secondary-fixed':      '#141b2b',
        'on-secondary-fixed-variant':'#404758',
        tertiary:                  '#6a1edb',
        'tertiary-container':      '#8343f4',
        'tertiary-fixed':          '#eaddff',
        'tertiary-fixed-dim':      '#d2bbff',
        'on-tertiary':             '#ffffff',
        'on-tertiary-container':   '#f7edff',
        'on-tertiary-fixed':       '#25005a',
        'on-tertiary-fixed-variant':'#5a00c6',
        error:                     '#ba1a1a',
        'error-container':         '#ffdad6',
        'on-error':                '#ffffff',
        'on-error-container':      '#93000a',
        outline:                   '#737686',
        'outline-variant':         '#c3c6d7',
        background:                '#f9f9ff',
        'on-background':           '#151c27',
        // Legacy aliases for existing components
        canvas:                    '#f9f9ff',
        'canvas-raised':           '#f0f3ff',
        'canvas-container':        '#e7eefe',
        'canvas-white':            '#ffffff',
        ink:                       '#151c27',
        'ink-muted':               '#434655',
        'ink-faint':               'rgba(67,70,85,0.12)',
        accent:                    '#004ac6',
        'accent-2':                '#2563eb',
        'accent-hover':            '#003da8',
        'input-fill':              '#e2e8f8',
      },
      fontFamily: {
        display:  ['Manrope', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '8px',
        sm:      '4px',
        md:      '8px',
        lg:      '16px',
        xl:      '24px',
        '2xl':   '32px',
        pill:    '9999px',
        full:    '9999px',
      },
      boxShadow: {
        premium: '0px 24px 48px -12px rgba(21, 28, 39, 0.08)',
        card:    '0px 8px 24px -4px rgba(21, 28, 39, 0.06)',
        btn:     '0 8px 24px rgba(0, 74, 198, 0.35)',
      },
      maxWidth: {
        content: '1280px',
      },
    },
  },
  plugins: [],
}

export default config
